### ISSUE TITLE
按照你的模板下载下来，jekyll serve时报错，怎么解决？

### ISSUE THREAD

**Issue by spring-guosheng** [leopardpan/leopardpan.github.io#28]
![Uploading image.png…]()
求教

**Comment by spring-guosheng** [comment]
图片不会上传啊，是显示

E:\互联网\jekyll博客>cd leopardpan.github.io-master

E:\互联网\jekyll博客\leopardpan.github.io-master>gem install bundler
Successfully installed bundler-1.15.4
Parsing documentation for bundler-1.15.4
Done installing documentation for bundler after 3 seconds
1 gem installed

E:\互联网\jekyll博客\leopardpan.github.io-master>jekyll server
D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find sass-3.5.1 in any of the sources (Bundler::GemNotFound)
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.6.0/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.6.0/exe/jekyll:11:in `<top (required)>'
        from D:/Program Files/Ruby23-x64/bin/jekyll:22:in `load'
        from D:/Program Files/Ruby23-x64/bin/jekyll:22:in `<main>'

E:\互联网\jekyll博客\leopardpan.github.io-master>jekyll serve
D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find sass-3.5.1 in any of the sources (Bundler::GemNotFound)
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.6.0/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
        from D:/Program Files/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.6.0/exe/jekyll:11:in `<top (required)>'
        from D:/Program Files/Ruby23-x64/bin/jekyll:22:in `load'
        from D:/Program Files/Ruby23-x64/bin/jekyll:22:in `<main>'
和之前一个人的问题类似，你给他的回答是安装bundler,我安装了没解决、。

**Comment by lhz1995** [comment]
sass 没装吧，gem install sass

**Comment by ridgew** [comment]
在代码目录下执行"bundler install"，就会自动安装jekyll所依赖的所有gem包，我在MacOS下执行成功，在windows下卡在了
```
Fetching redcarpet 3.4.0
Installing redcarpet 3.4.0 with native extensions
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/ui/shell.rb:125:in `[]': invalid byte sequence in UTF-8 (ArgumentError)
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/ui/shell.rb:125:in `strip_leading_spaces'
```
不知道是不是安装Ruby Installer的时候，默认勾选了UTF-8编码，重新安装Ruby问题依旧，估计要卸载再试了。

**Comment by gengzhaoyun** [comment]
bundle install
bundle exec jekyll serve

**Comment by gengzhaoyun** [comment]
@ridgew 
你用旧的版本试试吧，我按照这个可以正常使用
https://www.jianshu.com/p/88e3474cef72

启动的时候可能需要执行：
bundle install
bundle exec jekyll serve

**Comment by myifeng** [comment]
安装以后用`gem list`还要见车你安装的版本，与Gemfile.lock中的版本是否一致。

**Comment by syt-honey** [comment]
你好，我在使用这个模板的时候遇见了下面的问题：

1.进入clone目录(D:\Blog\mysite)后，打开Jekyll serve出现下面这个问题。

GitBash代码:
-----------------------------------------------------------------------------------------
honeysyt@DESKTOP-BEMCKJ5 MINGW64 /d/Blog/mysite (master)
$ jekyll serve
D:/rubyInstall/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/sp                                                                                                                ec_set.rb:88:in `block in materialize': Could not find ffi-1.9.18 in any of the                                                                                                                 sources (Bundler::GemNotFound)
        from D:/rubyInstall/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/l                                                                                                                ib/bundler/spec_set.rb:82:in `map!'
        from D:/rubyInstall/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/l                                                                                                                ib/bundler/spec_set.rb:82:in `materialize'
        from D:/rubyInstall/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/l                                                                                                                ib/bundler/definition.rb:170:in `specs'
        from D:/rubyInstall/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/l                                                                                                                ib/bundler/definition.rb:237:in `specs_for'
        from D:/rubyInstall/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/l                                                                                                                ib/bundler/definition.rb:226:in `requested_specs'
        from D:/rubyInstall/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/l                                                                                                                ib/bundler/runtime.rb:108:in `block in definition_method'
        from D:/rubyInstall/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/l                                                                                                                ib/bundler/runtime.rb:20:in `setup'
        from D:/rubyInstall/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/l                                                                                                                ib/bundler.rb:107:in `setup'
        from D:/rubyInstall/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib                                                                                                                /jekyll/plugin_manager.rb:50:in `require_from_bundler'
        from D:/rubyInstall/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/exe                                                                                                                /jekyll:11:in `<top (required)>'
        from D:/rubyInstall/Ruby25-x64/bin/jekyll:23:in `load'
        from D:/rubyInstall/Ruby25-x64/bin/jekyll:23:in `<main>'
----------------------------------------------------------------------------------------------------------

ps:看很多网友评论都说是gem包没有装全，于是我查看了gem list：
GitBash代码：
----------------------------------------------------------------------------------------------------------
addressable (2.5.2)
bigdecimal (default: 1.3.4)
bundle (0.0.1)
bundler (1.16.1)
cmath (default: 1.0.0)
colorator (1.1.0)
concurrent-ruby (1.0.5)
csv (default: 1.0.0)
date (default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.2.0)
em-websocket (0.5.1)
etc (default: 1.0.0)
eventmachine (1.2.5 x64-mingw32)
fcntl (default: 1.0.0)
ffi (1.9.23 x64-mingw32)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
forwardable-extended (2.6.0)
gdbm (default: 2.0.0)
http_parser.rb (0.6.0)
i18n (0.9.5)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
jekyll (3.7.3)
jekyll-sass-converter (1.5.2)
jekyll-watch (2.0.0)
json (default: 2.1.0)
kramdown (1.16.2)
liquid (4.0.0)
listen (3.1.5)
mercenary (0.3.6)
minitest (5.10.3)
net-telnet (0.1.1)
openssl (default: 2.1.0)
pathutil (0.16.1)
power_assert (1.1.1)
psych (default: 3.0.2)
public_suffix (3.0.2, 3.0.0)
rake (12.3.0)
rb-fsevent (0.10.3)
rb-inotify (0.9.10)
rdoc (default: 6.0.1)
rouge (3.1.1)
ruby_dep (1.5.0)
safe_yaml (1.0.4)
sass (3.5.6)
sass-listen (4.0.0)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
test-unit (3.2.7)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
zlib (default: 1.0.0)

---------------------------------------------------------------------------------------------------------

**Comment by myifeng** [comment]
@syt-honey 这是你的版本和Gemfile.lock文件里的版本不一致引起的。请参看[使用GitHub+Jekyll搭建个人博客](https://myifeng.github.io/)

**Comment by syt-honey** [comment]
@myifeng 谢谢呀，我把相应的Gemfile.lock文件里的版本都相应的做了修改，但是出现了这种情况：
---
honeysyt@DESKTOP-BEMCKJ5 MINGW64 /d/Blog/mysite (master)
$ jekyll s
Configuration file: D:/Blog/mysite/_config.yml
            Source: D:/Blog/mysite
       Destination: D:/Blog/mysite/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 2.81 seconds.
  Dependency Error: Yikes! It looks like you don't have jekyll-watch or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- ruby_dep/warning' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
jekyll 3.7.3 | Error:  jekyll-watch
---

我找了些相应的资料都没能解决。找到一个相似的，按照他的这种做法试了一下，也没用：
---
ERROR:  Could not find a valid gem 'GEM_NAME_HERE' (>= 0) in any repository
ERROR:  Possible alternatives: gemometer
---
由于我没查到关于这个命令的信息，也不知道怎么解决。如果你知道的话，麻烦告诉我一下呀，谢谢~
https://stackoverflow.com/questions/33524443/jekyll-cannot-load-such-file-jekyll-watch

**Comment by myifeng** [comment]
@syt-honey 缺少`cannot load such file -- ruby_dep/warning`，缺少`ruby_dep` 使用`gem list`查看是已经安装`ruby_dep`,如果没有使用`gem install ruby_dep`安装

**Comment by syt-honey** [comment]
@myifeng 安装了呀，提示说缺少依赖包，但是这个依赖包是个啥我都没找着资料……

**Comment by syt-honey** [comment]
@myifeng 嘿， 这个问题我已经解决了。是因为gem包不全引起的，我在我的repo上已经更新了，谢谢你的耐心回答！

**Comment by huangzijian888** [comment]
@syt-honey 我也遇到了你类似的问题 请问你最后是怎么解决的 
![2018-05-09 11 03 04](https://user-images.githubusercontent.com/25848688/39793571-94d6ec06-5378-11e8-8fdb-0fe07cbaa51e.png)

**Comment by syt-honey** [comment]
@huangzijian888 我最后是在stackoverflow上提问了才解决的这个问题。他帮我写了一个pull request[在这里](https://github.com/syt-honey/blogs.github.io/pull/1)，我merge之后就可以了。

**Comment by huangzijian888** [comment]
@syt-honey 好的谢谢小姐姐

**Comment by syt-honey** [comment]
@huangzijian888 哈喽，你弄好了嘛?我今天下午试了一下，可以的。你不要fork我的哈，我的评论不知道咋的有问题，我还要研究一下，如果你没弄好的话我可以把文件发你邮箱里~

**Comment by huangzijian888** [comment]
@syt-honey  哈喽，小姐姐。我昨天看了一下@ashmaroli给你写的那个pull 已经解决了 博客现在已经上线了 功能还有待完善 有兴趣的话我们可以交流下

**Comment by yuqianglianshou** [comment]
$ jekyll server
D:/bokeabout/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/resolver.rb:289:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'redcarpet x64-mingw32' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
        from D:/bokeabout/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/resolver.rb:257:in `each'
        from D:/bokeabout/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/resolver.rb:257:in `verify_gemfile_dependencies_are_found!'
        from D:/bokeabout/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/resolver.rb:48:in `start'
        from D:/bokeabout/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/resolver.rb:22:in `resolve'
        from D:/bokeabout/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/definition.rb:258:in `resolve'
        from D:/bokeabout/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/definition.rb:171:in `specs'
        from D:/bokeabout/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/definition.rb:238:in `specs_for'
        from D:/bokeabout/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/definition.rb:227:in `requested_specs'
        from D:/bokeabout/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:108:in `block in definition_method'
        from D:/bokeabout/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:20:in `setup'
        from D:/bokeabout/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler.rb:107:in `setup'
        from D:/bokeabout/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.8.3/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
        from D:/bokeabout/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.8.3/exe/jekyll:11:in `<top (required)>'
        from D:/bokeabout/Ruby24-x64/bin/jekyll:23:in `load'
        from D:/bokeabout/Ruby24-x64/bin/jekyll:23:in `<main>'
自己new博客没问题，http://127.0.0.1:4000/能打开也能看到，但是clone你的就报错了，在 jekyll server这一步，弄了一晚上了，实在没明白怎么回事

**Comment by huangzijian888** [comment]
@yuqianglianshou gem包不全

**Comment by yuqianglianshou** [comment]
@huangzijian888 是这样，谢谢

**Comment by frankda** [comment]
@spring-guosheng 你好，我也遇到同样的问题，不过缺失的时jemoji。描述如下：
  Dependency Error: Yikes! It looks like you don't have jemoji or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jemoji' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
你在回答中的链接404了，麻烦问下你时如何把相应的gem包安装上的呢？

**Comment by KSMASTERS** [comment]
D:\document\leopardpan.github.io>jekyll server
Traceback (most recent call last):
        12: from C:/Ruby25-x64/bin/jekyll:23:in `<main>'
        11: from C:/Ruby25-x64/bin/jekyll:23:in `load'
        10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.8.4/exe/jekyll:11:in `<top (required)>'
         9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.8.4/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
         8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler.rb:107:in `setup'
         7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:20:in `setup'
         6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:108:in `block in definition_method'
         5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/definition.rb:227:in `requested_specs'
         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/definition.rb:238:in `specs_for'
         3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/definition.rb:171:in `specs'
         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/spec_set.rb:85:in `materialize'
         1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/spec_set.rb:85:in `map!'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find public_suffix-3.0.0 in any of the sources (Bundler::GemNotFound)

这个是我报的错，请问这是因为什么问题啊，很晚了，我要开始睡觉了，第二天还要上班QAQ，谢谢大神！

**Comment by KSMASTERS** [comment]
已经解决了，bundle update就可以了，如果是缺少依赖的话，都可以这样解决的吧

**Comment by Yup-China** [comment]
我在执行jekyll serve 遇到这个问题一直解决不了，百度了试了一些方法也不行，有没有哥哥姐姐帮忙看看。

E:\yupg\leopardpan.github.io-master>jekyll serve
Traceback (most recent call last):
        12: from E:/ruby/ruby2.5.7-x64/Ruby25-x64/bin/jekyll:23:in `<main>'
        11: from E:/ruby/ruby2.5.7-x64/Ruby25-x64/bin/jekyll:23:in `load'
        10: from E:/ruby/ruby2.5.7-x64/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/exe/jekyll:11:in `<top (required)>'
         9: from E:/ruby/ruby2.5.7-x64/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
         8: from E:/ruby/ruby2.5.7-x64/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
         7: from E:/ruby/ruby2.5.7-x64/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
         6: from E:/ruby/ruby2.5.7-x64/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
         5: from E:/ruby/ruby2.5.7-x64/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
         4: from E:/ruby/ruby2.5.7-x64/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
         3: from E:/ruby/ruby2.5.7-x64/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
         2: from E:/ruby/ruby2.5.7-x64/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `materialize'
         1: from E:/ruby/ruby2.5.7-x64/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `map!'
E:/ruby/ruby2.5.7-x64/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find public_suffix-3.0.3 in any of the sources (Bundler::GemNotFound)
